# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

common: &common
  eventbrite_token: <%= ENV["EVENTBRITE_TOKEN"] %>
  meetup_key: <%= ENV['MEETUP_KEY'] %>

development:
  <<: *common
  secret_key_base: 302d8a13fd1ec51ca6ee8e01c0da1b7e0b060431f0b0e5975de37f1a316d8bc73f24ec53e9d0d8276db196187d5f98ba8db73cabbc6d3938739d442ea7db1157
  admin_password: 'pass'

test:
  <<: *common
  secret_key_base: 83256a0104a6894a10d68f527f181f2a6fd1f1af3bbc6c3019b150b440640a1a79c4a91d010443f4889a618a77720c12915c38e8413dbf66fa8e393f048b26a3
  admin_password: 'pass'

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  <<: *common
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  admin_password: <%= ENV["ADMIN_PASSOWRD"] %>
  admin_password: <%= ENV["ADMIN_PASSOWRD"] %>
